### ISSUE TITLE
Return 64 byte secret key for ed25519

### ISSUE THREAD

**Issue by AndreaScorza** [ltonetwork/lto-api.python#15]
The CreateFromPrivateKey, uses the 64 bytes long PrivKey from the wallet to create the account when the PrivKey in input is not an object. 
It would be beneficial to implement the 64 bytes long key not only for the wallet but also for the API in order to be able to recover the PublicKey, also there are a lot of conversion throughout the API for the transaction (ex the GetPublicKey method).
the way the Private and Public Key are stored should be unified for the whole API, and the conversion minimized.

**Comment by jasny** [comment]
???

**Comment by trlaing** [comment]
> The python library returns a 32-byte secret key for ed25519. It needs to return a 64-byte secret key.

I have a 64-byte private key that I need to use with a Python method that only accepts a 32-byte private (or secret) key. How can I convert this 64-byte key to a 32-byte key please?
