### ISSUE TITLE
Add api_key in public node constructor

### ISSUE THREAD

**Issue by KaloyanTanev** [ltonetwork/lto-api.python#24]
Usually for some calls to the node, we need an api key, which we currently cannot provide when creating Public Node. You can check how I add it in the `http_requests.py` file in the e2e tests.

**Comment by AndreaScorza** [comment]
Could you provide an example? if there is the end point I will add the API

**Comment by KaloyanTanev** [comment]
This endpoint `/transactions/sign` requires API key for example. It's not about adding an endpoint but auth key.

**Comment by AndreaScorza** [comment]
When we sign we do have all the necessary information, I don't see your point

**Comment by KaloyanTanev** [comment]
https://swagger.io/docs/specification/authentication/api-keys/
