### ISSUE TITLE
Stick to Python naming conventions throughout the whole API

### ISSUE THREAD

**Issue by KaloyanTanev** [ltonetwork/lto-api.python#25]
https://www.python.org/dev/peps/pep-0008/

**Comment by AndreaScorza** [comment]
We opted for consistency with the rest of the APIs

**Comment by KaloyanTanev** [comment]
Hmmm... I suppose a developer integrating LTO to their backend wouldn't use at all LTO's Scala/Java/PHP/JavaScript API, as their backend is in Python. Moreover, most likely all of the Python codebase they have would be as described in `pep-0008` (it's been standard for >10 years), making the LTO library the inconsistent part.

**Comment by jasny** [comment]
@KaloyanTanev Can you give examples of where the naming convention is wrong?

**Comment by KaloyanTanev** [comment]
As a start - the functions throughout the whole API, they should be snake_case, instead of camelCase.

**Comment by KaloyanTanev** [comment]
Package names should also be snake_case. Here is a table to ease your work with the naming conventions
<img width="708" alt="Screenshot 2021-11-17 at 11 01 15" src="https://user-images.githubusercontent.com/24719519/142188573-9028adc2-c3fd-4b44-ad8c-66216ad1e0bc.png">

And for further PRs, please lets:
1. Let someone review and approve the PR before merging
2. Keep PRs simple and with single purpose - it's easier to review and revert if necessary. If not that, at least some description what the PR includes
