### ISSUE TITLE
Tests won't run on latest Python 3.9

### ISSUE THREAD

**Issue by jasny** [ltonetwork/lto-api.python#65]
The issue presented itself with Travis, but might be a general issue with the latest python version.

> The build of our project on Python 3.9 is suddenly failing. There is no change between this build and the previous one that's succeeding. It seems to be a change or bug in the python 3.9 environment on Travis.
>
> https://app.travis-ci.com/github/ltonetwork/lto-api.python/jobs/562273827

It seems like your build is started failing due to the default version that Python3.9 is providing. You can also see the change on the diff [1] that I have created as well. So in this case I would recommend you to pin the specific Python version "3.9.5" within your .travis.yml file.

**Comment by mustafa-travisci** [comment]
#66 might help in this case.
